### ISSUE TITLE
The value of the language is changed automatically when editing the activity

### ISSUE THREAD

**Issue by sarjona** [projectestac/moodle-mod_geogebra#13]
Josep Lluís Cañadilla has reported this bug:

Una cosa a millorar és la següent, encara que no es faci, sí que s'hauria d'anotar en algun lloc com a pendent de fer.

1.- Si obriu en el GeoGebraTube una construcció amb JavaScript (per exemple http://www.geogebratube.org/student/m11784)
Veureu que en el codi font de la pàgina html no apareix codi javascript. Deu estar dins el code64??? I el parametre lenguage no hi es

2.- Si accediu al nostre espai de proves http://phobos.xtec.cat/dpllphp1/moodle/course/view.php?id=6
Dins el tema 5 apartat material en castellà, activitat baricentro , accediu-hi i mireu el codi font de l'html. Sí que apareix el codi javascript. Observeu de pas que el paràmetre lenguage=es.

3.- Torneu al curs. Activeu edició. Editeu l'activitat anterior. Veureu que el desplegable està en català en comptes de l'espanyol???. Deseu sense fer cap canvi i accediu a l'activitat. Mireu el codi font html i veureu que l'idioma s'ha canviat a català. (languege="ca") i no hem fet cap canvi voluntàriament.

**Comment by crazyserver** [comment]
Resolta per la versió 2.8
