### ISSUE TITLE
Codi javascript dels objectes

### ISSUE THREAD

**Issue by jcanadil** [projectestac/moodle-mod_geogebra#20]
El codi javascript que s'introdueix en les pestanyes Al clicar o Al modificar d'un objecte (en les propietats de l'objecte) no apareix en el codi html de la pàgina web de Moodle. Hauria de sortir com a funció del tipus function ggbicon1() {} sota de function ggbOnInit(){}

**Comment by crazyserver** [comment]
Hola Josep,

seguint el fil de conversa que vas tenir en el seu moment amb la Sara no em queda clar com provar aquest. Tot i així necessitaria, si us plau, que provessis la darrera versió qua hi ha al git i ens diguessis si encara tens el mateix problema.

Moltes gràcies!

Pau

**Comment by jcanadil** [comment]
Hola Pau

D'això ja fa molt de temps. No recordo de què anava.

Ja fa temps que no faig servir aquest tipus d'activitats dins el Moodle. Des de què vam actualitzar la versió del Moodle al meu centre ino era compatible amb aquest tipologia d'activitats.

Si vols que faci alguna cosa... M'ho dius. 

Salutacions
Josep Lluís

Enviat des del meu iPhone

El 14/07/2015, a les 9:41, Pau Ferrer Ocaña <notifications@github.com> va escriure:

**Comment by crazyserver** [comment]
Doncs tanco perquè crec que ja està resolt... una llàstima que no el facis servir! 

Salut!

Pau

**Comment by jcanadil** [comment]
Hola Pau

Fa uns dies, un conegut em va preguntar sobre el mòdul GeoGebra per al
Moodle. Tenia uns dubtes i volia solucionar-los (no li funcionava la
aleatorietat).

He instal·lat el pluguin al Moodle del meu centre (2.9.1) per fer-hi proves
(i poder ajudar-lo)  i no aconsegueixo que es carregui l'applet (es queda
pensant).

Saps que pot ser?


Una altra cosa. Com està el mòdul? Es segueix treballant per
perfeccionar-lo o ampliar-lo?

Salutacions
Josep Lluís Cañadilla

El dia 14 de juliol de 2015, 9:41, Pau Ferrer Ocaña <
notifications@github.com> ha escrit:
