### ISSUE TITLE
Qualificació per aprovar

### ISSUE THREAD

**Issue by raulfh** [projectestac/moodle-mod_geogebra#26]
A la nova versió (per a Moodle 2.8), quan tries que sigui autopuntuable, llavors et reclama una puntuació mínima per aprovar.
Per defecte apareix 0,00
Quan poses 5,00, no ho accepta com a número. Poses 5 (a seques) i ho accepta.
PERÒ quan tornes a entrar, torna a posar 5,00, i clar, al acceptar, dóna l'error anterior, i has de tornar a posar 5

**Comment by raulfh** [comment]
Oblideu-lo, el mateix error es replica a altres activitat, de manera que crec que és un error de Moodle ("és d'ells")

**Comment by crazyserver** [comment]
Crec q es cosa del locale, prova posar 5.00 ;-) canviant la coma pel punt
