### ISSUE TITLE
JavaScript global

### ISSUE THREAD

**Issue by raulfh** [projectestac/moodle-mod_geogebra#27]
Hola, sembla que amb la nova versió NO està executant el que hi ha al JS global, és a dir, el que es posa en qualsevol objecte en el ggbOnInit().
És per això que no es pot fer servir el truc per fixar variables aleatòries.
Caldria una alternativa per fixar randoms, de manera que només en una primera execució de la applet, quedés fixada, i que en fer un ALTRE intent, llavors tornés a fer un random.

Si fas servir el random de GeoGebra, fent F5 tens valors nous.

**Comment by raulfh** [comment]
Fent el RandomBetween[0,10,true] no soluciona el problema.

**Comment by crazyserver** [comment]
Gràcies raulfh!  Necessiraríem més infomació, no acabo d'entendre de que no s'executa ni quan ni com provar-ho...

Gràcies!!

**Comment by crazyserver** [comment]
Trobat, farem proves i us diem. Si teniu alguna activitat localitzada i ens podeu passar l'enllaç (si és privada, per correu) ens anirà genial! :dancers:

**Comment by raulfh** [comment]
Hola, justament vaig estar fent proves amb aquest.
Simplement assigna la variable grade a 5.5.
L'efecte és que quan l'obres, el grade=0, tal i com deses el fitxer. Però
al executar-lo, llavors grade=5.5



Raül Fernández
http://about.me/raulf

2015-07-07 10:45 GMT+02:00 Pau Ferrer Ocaña <notifications@github.com>:

**Comment by raulfh** [comment]
WORKS!!!
A lot of thanks crack!
