### ISSUE TITLE
Installation error on Moodle 2.4.11

### ISSUE THREAD

**Issue by iacomellig** [projectestac/moodle-mod_geogebra#28]
This is the error message when installing geogebra on moodle 2.4.11

![error geogebra](https://cloud.githubusercontent.com/assets/14927488/10225839/e23a63a8-6864-11e5-987d-7e2351b18870.gif)

Could you help me?

**Comment by sarjona** [comment]
Could you tell us which version of GeoGebra module are you trying to install? Have you tried some of the "public versions" from moodle.org: https://moodle.org/plugins/view/mod_geogebra ?

**Comment by iacomellig** [comment]
Thanks for your intereset, but I have resolved the problem.
My first failed attempt was with version mod_geogebra_moodle26_2014052900 
but after that i have tried with moodle-mod_geogebra-MOODLE_24_STABLE and that's ok.

Thanks
Guglielmo Iacomelli

**Comment by crazyserver** [comment]
Thats great! :D Thanks for your comments! :D
