### ISSUE TITLE
No se ejecuta codigo javascript incorporado en la construcción

### ISSUE THREAD

**Issue by jcanadil** [projectestac/moodle-mod_geogebra#30]
He instalado el módulo en un Moodle 2.9.1 y el código javascript que contienen los archivos ggb no se ejecuta. 

En el archivo locallib.php de v0.2.7 (2015061500) no aparecen las líneas 320-321 y 326-397 del mismo archivo que aparecen en https://github.com/projectestac/moodle-mod_geogebra/blob/master/locallib.php que están destinadas a incluir el código javascript contenido en los archovos ggb.¿?

He hecho diferentes pruebas añadiento este código (líneas 320-321 y 326-397), però no me ha funcionado. He mirado ejemplos en GeoGebraTube y he observado que en el código html se añade el parámetro useBrowserForJS:false

Yo he añadido este parámetro en la línea 307 de locallib.php en mi Moodle  quedando de la siguiente forma:
var applet = new GGBApplet({useBrowserForJS:false';

Funciona perfectamente, aparentemente, todo el módulo y se ejecuta el código javascript excepto quando la construcción ggb contiene código javascript en la javascriptGlobal. En este caso, se ejecuta el código javascript peró los botones Guardar y Entregar no funcionan.

**Comment by crazyserver** [comment]
Hola! Estas usando la versión del directorio de plugins?

Puedes probar la que tenemos aqui en el git y decirnos si con eso funciona?

Un saludo y gracias por el aviso!

Pau

**Comment by crazyserver** [comment]
Hemos liberado la versió 0.2.7.1 que corresponde al master actual ;)

**Comment by jcanadil** [comment]
Hola Pau!


He utilizado la versión que hay en la página web del Moodle (directorio de
plugins).

Saludos
José Luis Cañadilla

2015-10-15 14:15 GMT+02:00 Pau Ferrer Ocaña <notifications@github.com>:

**Comment by jcanadil** [comment]
Hola Pau!

Muchas gracias por la pronta intervención.

He actualizado el módulo a la versión 0.2.7.1 y en la primeras pruebas
funciona el javascript que hay en el Global Script. No así el que hay
asociado a los objetos en la pestaña Al clicar o Al actualizar.

Haré algunas pruebas más.

Saludos
José Luis Cañadilla

2015-10-15 14:28 GMT+02:00 Pau Ferrer Ocaña <notifications@github.com>:

**Comment by jcanadil** [comment]
Hola
Confirmado el módulo no permite ejecutar codigo javascript que esté en Al
clicar o Al actualizar de un objecto.

Adjunto construcción de prueba.
Consta de un punto A y dos botones.
Cuando se carga la construcción se ejecuta correctamente el codigo
javaScript contenido en GlobalScript que crea un punto C
Cuando se clica sobre el segundo botón se crea el punto D con codigo
GeoGebra Script (ningún problema).
Cuando se clica sobre el primer botón se NO se crea el punto C a partir del
código javascript.

Saludos
José Luis Cañadilla

2015-10-15 17:01 GMT+02:00 JOSE LUIS CAÑADILLA LOPEZ DE COCA <
jcanadil@xtec.cat>:

**Comment by jcanadil** [comment]
Si a la nueva versión 0.2.7.1 se modifica el archivo locallib.php en la línia 307:
Substituir: 
var applet = new GGBApplet({';

Por:
var applet = new GGBApplet({useBrowserForJS: false,';

**Comment by crazyserver** [comment]
Hola José Luís,

Gracias por tus aportaciones, estudiaremos el caso.
Por otro lado, puedes adjuntar de nuevo los archivos? Si contestas por email no funciona, se ha de hacer desde la web de github.

Gracias!

Pau

**Comment by jcanadil** [comment]
Hola 
No puedo , o no sé, subir un fichero ggb.
Saludos
José Luis

**Comment by crazyserver** [comment]
Hola,
Si quieres envíanos el archivo a agora@xtec.cat, indica que va dirigido a mi.
Un saludo,
Pau

**Comment by crazyserver** [comment]
Gracias José Luis. Solucionado en la v0.2.7.2
