### ISSUE TITLE
Ús de la funció 'deprecated' moodleform_mod::add_intro_editor 

### ISSUE THREAD

**Issue by reskit** [projectestac/moodle-mod_geogebra#32]
Des de la versió de Moodle 2.9 no s'ha de fer servir la funció add_intro_editor, en el seu lloc cal fer servir la funció standard_intro_elements. Podeu trobar més informació a https://tracker.moodle.org/browse/MDL-49101

**Comment by sarjona** [comment]
@reskit Gràcies per l'avís!! Hem creat branca per la 2.8 (perquè allà no funciona el canvi i hem aplicat el canvi a la màster :-)
