### ISSUE TITLE
No grading with Moodle 3.1

### ISSUE THREAD

**Issue by raven3k** [projectestac/moodle-mod_geogebra#33]
It is not possible to store Grade results with mod_geogebra (2016052000) 
The values Grade and Comment with mod_geogebra are not saved after submit.

![moodle31_geogebra_activity_grader](https://cloud.githubusercontent.com/assets/6396516/16116121/745189ba-33cb-11e6-9154-dd50173e6820.png)

**Comment by sarjona** [comment]
Hi raven3k!

Your comments are related to "GeoGebra submissions" plugin (https://moodle.org/plugins/assignsubmission_geogebra) which is mantained by another team (the International GeoGebra Institute). Our GeoGebra plugin is this https://moodle.org/plugins/mod_geogebra and it's working correctly for Moodle 3.1 (in fact, some days ago we got the [Early bird 3.1 badge](https://moodle.org/plugins/browse.php?list=award&id=4))

Best wishes from Barcelona!

**Comment by raven3k** [comment]
my post is edited. The GeoGebra Submissions related Infos are now in the correct issue thread for the another team.

**Comment by sarjona** [comment]
Great! We hope they can help you to fix this problem. 

Please, let us know if you find some bug or improvement to our plugin :-)

**Comment by raven3k** [comment]
maybe i use the activity wrong.
I have a result and write a comment and set a score, that will not be saved. And this is normaly?

**Comment by sarjona** [comment]
Hi raven3k!

Thanks for your comments. With your instructions we can now reproduce the error and we'll try to fix as soon as possible.

Keep in touch! :-)

**Comment by sarjona** [comment]
Hi Patrick!

Error fixed int the commit https://github.com/projectestac/moodle-mod_geogebra/commit/8cccb9e23df9c58e4f693eb90a547fc9df025294

We've uploaded a new version for Moodle 3.0 and 3.1 which can be downloaded from https://moodle.org/plugins/pluginversion.php?id=11572

Thanks for helping us to improve this module! :-)

**Comment by raven3k** [comment]
Thanks for the fast Fix.

But please add in the file locallib.php 1350
` $result = new stdClass();`

**Comment by sarjona** [comment]
Thanks again for your comment.

We've added this var declaration to the code. So, if you get the version from GitHub it will be right.
