### ISSUE TITLE
branches

### ISSUE THREAD

**Issue by pfautrero** [projectestac/moodle-mod_geogebra#35]
Hi,
Is it possible to have the MOODLE_31_STABLE branch in this repository ? I have seen that your plugin is already available for moodle 3.0 and moodle 3.1 here https://moodle.org/plugins/view.php?plugin=mod_geogebra&moodle_version=23

Thanks

**Comment by sarjona** [comment]
Done! :-)

https://github.com/projectestac/moodle-mod_geogebra/tree/MOODLE_31_STABLE
