### ISSUE TITLE
moodle 3.1 issue

### ISSUE THREAD

**Issue by pfautrero** [projectestac/moodle-mod_geogebra#36]
Hi, 

I have created a new geogebra activity in a new course and when I visit the course/view.php page, here what I have get :

 **Invalid component used in plugin/component_callback():mod_geogebra**

```
Stack trace: 

    line 7458 of /lib/moodlelib.php: coding_exception thrown
    line 1274 of /course/lib.php: call to component_callback_exists()
    line 432 of /course/renderer.php: call to get_module_metadata()
    line 868 of /course/format/renderer.php: call to core_course_renderer->course_section_add_cm_control()
    line 56 of /course/format/topics/format.php: call to format_section_renderer_base->print_multiple_section_page()
    line 280 of /course/view.php: call to require()
```

any idea ?

**Comment by sarjona** [comment]
Hi!

I have never seen this error before :-( Could you give us more information about your installation (Moodle version, GeoGebra version, database engine, server engine...) to try to help you? :-)

Kind regards,
Sara

**Comment by toniginard** [comment]
There is not enough information to reproduce it. The question is also regarding an old version of Moodle, so I close the issue.
