### ISSUE TITLE
Need help to design a question using Geogebra qtype for Moodle 3.1

### ISSUE THREAD

**Issue by gsovis** [projectestac/moodle-mod_geogebra#37]
I am trying to design a question using Geogebra Question type using the worksheet at
[https://www.geogebra.org/m/qpbbUN6a].
My Moodle version is 3.1.
Can you please post a help file in English or a sample question, so that we could follow the steps?
Thanking you in advance.

**Comment by sarjona** [comment]
Hi @gsovis !!

We're the maintainers of the GeoGebra plugin (https://moodle.org/plugins/mod_geogebra), which is a new activity type. The maintainer of the GeoGebra question type (https://moodle.org/plugins/qtype_geogebra) is the International GeoGebra Institute.

If you need some help about the question type is better you contact with them ;-)

Best wishes from Barcelona,
Sara
