### ISSUE TITLE
Moodle 3.6.1 Error debugging on - off blank page 

### ISSUE THREAD

**Issue by juerghoerner** [projectestac/moodle-mod_geogebra#39]
mod geogebra when debugging is on  
Warning: require_once(/var/www/lmsMyPage/moodle/lib/eventslib.php): failed to open stream: No such file or directory in /var/www/lmsMyPage/moodle/mod/geogebra/lib.php on line 54

Fatal error: require_once(): Failed opening required '/var/www/lmsMyPage/moodle/lib/eventslib.php' (include_path='/var/www/lmsMyPage/moodle/lib/pear:.:/usr/share/php') in /var/www/lmsMyPage/moodle/mod/geogebra/lib.php on line 54

**Comment by MarcCeleiro** [comment]
Same here with all the XTEC plugins (JClic, GeoGebra & QV).

```
Warning: require_once(/var/www/vhosts/insatorroja.cat/campus/lib/eventslib.php): failed to open stream: No such file or directory in /var/www/vhosts/insatorroja.cat/campus/mod/geogebra/lib.php on line 54

Fatal error: require_once(): Failed opening required '/var/www/vhosts/insatorroja.cat/campus/lib/eventslib.php' (include_path='/var/www/vhosts/insatorroja.cat/campus/lib/pear:.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/insatorroja.cat/campus/mod/geogebra/lib.php on line 54
```

The solution for me was delete all the folders from those plugins placed inside the mod/ folder.

**Comment by juerghoerner** [comment]
My solution: I commented out the line 54 in the mod/geogebra/lib.php  with // 
It seems, all works fine.

**Comment by MarcCeleiro** [comment]
> 
> 
> My solution: I commented out the line 54 in the mod/geogebra/lib.php with //
> It seems, all works fine.

At the moment, this solution works for me too, although I suppose that this line of code must be important for the proper functioning of those add-ons. I'll leave them with the commented line waiting for an update from the XTEC team.

**Comment by frncesc** [comment]
Thanks for reporting!

Commit [41192dd](https://github.com/projectestac/moodle-mod_geogebra/commit/41192ddfb27b4548d49fb86f1f9a923ee79c01ea) solves this problem with Moodle 3.6.

`eventslib.php` (required in `lib.php`, but not  actually used in this plugin) was deprecated and removed in Moodle 3.6. See: https://docs.moodle.org/dev/Events_API

Same issue, now already solved, was found in [moodle-mod_jclic](https://github.com/projectestac/moodle-mod_jclic).

**Comment by MarcCeleiro** [comment]
@frncesc Remember to upload the latest version in the Moodle plugins site ;) https://moodle.org/plugins/pluginversions.php?plugin=mod_geogebra
