### ISSUE TITLE
eMail-Adresse wird angezeigt

### ISSUE THREAD

**Issue by andreasschenkel** [projectestac/moodle-mod_geogebra#41]
Wenn man sich als Trainer die Ergebnisse anzeigen lässt, dann wird neben dem Namen des Schülers auch dessen eMail-Adresse angezeigt. Das ist nicht zulässig und muss dringend geändert werden.
Oder kann man das irgendwo deaktivieren?

**Comment by andreasschenkel** [comment]
habe im quellcode in der Datei 
           locallib.php 
die Zeile
           echo $picture.' '.$userlink.' ('.$user->email.')';
geändert in
            echo $picture.' '.$userlink;

**Comment by andreasschenkel** [comment]
Ich meine mich zu erinnern, dass das behoben wurde, kann es aber aktuell nicht nachprüfen? Kann das auf "geschlossen" gesetzt werden?

**Comment by toniginard** [comment]
Change added in commit a2138fa9b7efd4a343fbc7addd6d652bb2553aef
