### ISSUE TITLE
Release compatible for Moodle 3.7?

### ISSUE THREAD

**Issue by mathieumd** [projectestac/moodle-mod_geogebra#43]
Hello,

When do you plan to release a version compatible with [Moodle 3.7](https://download.moodle.org/releases/latest/)?

Thanks for your work.

**Comment by toniginard** [comment]
There are currently no plans about it. Right now, the most likely date is next spring.

**Comment by mathieumd** [comment]
Thanks for that answer.

**Comment by andreasschenkel** [comment]
I installed mod_geogebra in moodle 3.7 and moodle 3.8 and it seams to work. Will there be updates so that the plugin "officially" supports this version? Will there be an update to moodle 3.9 when moodle 3.9 ist released in June 2020?
