### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by maxisnowhere** [projectestac/moodle-mod_geogebra#49]
Sorry if I write on the wrong place.

I would like to cooperate for an italian translation of this plugin, but I don't know where to beguin. 

I think I should prepare a folder like "moodle-mod_geogebra/lang/it/" with a geogebra.php file, where all the string are translated is it right/possibile?

Thank a lot and sorry if I write in the wrong place...
Max

**Comment by toniginard** [comment]
Hi Max,

Moodle provides a centralized translation center called AMOS:  [(https://lang.moodle.org/)]

All translation contributions must be done there. Moodle also provides a system inside Moodle to get the translations from the AMOS, so all the process can be done automatically.

To contribute, just log in one of the many ways the site provides, go to the AMOS translator, search the component (geogebra in this case) and translate online. Your contribution will stay in a pending state until a reviewer approves or rejects them. Once approved, they are integrated to the official language package.


Best wishes,

Toni Ginard
