### ISSUE TITLE
Submit and finish

### ISSUE THREAD

**Issue by Cristobal-84** [projectestac/moodle-mod_geogebra#50]
Hi,

For most of my GeoGebra activities the "Submit and Finish" button works intermittently, would you know why?
Is it due to my GeoGebra file or to your plugin?

**Comment by toniginard** [comment]
Was fixed in version v3.6.3

**Comment by Cristobal-84** [comment]
My institution only installs official edited versions at https://moodle.org/plugins/mod_geogebra
When will this be the case for version 3.6.3 or later ?
