### ISSUE TITLE
Randomization

### ISSUE THREAD

**Issue by TWINGSISTER** [projectestac/moodle-mod_geogebra#52]
Some GGB activities comes with randomization. This means that every time you take the test a slightly different version of the activity is presented. This is NEEDED to contrast cheating, nevertheless in many occasion teacher want to open an activity from Moodle and be sure that students will open in Moodle the same version of the exercise. I discussed options on the GGB forum and a wealth of solutions are possible. Some options require to pass a parameter to the GGB applet (see the files in the discussion [HERE](https://help.geogebra.org/topic/controlled-randomness-needed#comment-304660)). Now the question is: Is there any hope to see a request for merge accepted if I try to add some settings to this plugin so that users can have the option of randomize/not randomize some activities and also is this necessary or there are better ways to cope with this?

**Comment by TWINGSISTER** [comment]
I really needed this so I forked and implemented a basic control of randomization, a pull request is pending.
I also added parametrization of the GGB source.

**Comment by toniginard** [comment]
Your contributions have been integrated in versions v3.6.4 and v3.6.5. Many thanks!

**Comment by TWINGSISTER** [comment]
You Welcome, happy to have been useful!
