### ISSUE TITLE
Undefined property: stdClass::$timedue and stdClass::$grade

### ISSUE THREAD

**Issue by christina-roperto** [projectestac/moodle-mod_geogebra#57]
1) core_calendar_container_testcase::test_delete_module_delete_events
Undefined property: stdClass::$timedue

/var/www/site/mod/geogebra/locallib.php:61
/var/www/site/mod/geogebra/lib.php:127
/var/www/site/course/modlib.php:128
/var/www/site/lib/testing/generator/module_generator.php:271
/var/www/site/mod/geogebra/tests/generator/lib.php:49
/var/www/site/calendar/tests/container_test.php:445
/var/www/site/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "core_calendar_container_testcase" calendar/tests/container_test.php

Undefined property: stdClass::$grade
 /siteroot/mod/geogebra/lib.php:412
 /siteroot/mod/geogebra/locallib.php:90
 /siteroot/mod/geogebra/lib.php:127
 /siteroot/course/modlib.php:128
 /siteroot/lib/testing/generator/module_generator.php:271
 /siteroot/mod/geogebra/tests/generator/lib.php:49
 /siteroot/calendar/tests/container_test.php:445
 /siteroot/lib/phpunit/classes/advanced_testcase.php:80

I will submit a PR for this

**Comment by toniginard** [comment]
Fixed in https://github.com/projectestac/moodle-mod_geogebra/pull/58
