### ISSUE TITLE
Next official edited version

### ISSUE THREAD

**Issue by Cristobal-84** [projectestac/moodle-mod_geogebra#67]
You answered me in topic #50 that the problem has been fixed in version v3.6.3.
My institution only installs official edited versions at https://moodle.org/plugins/mod_geogebra
When will this be the case for version 3.6.3 or later?

**Comment by frncesc** [comment]
Updated the official Moodle plugins directory just now.

We apologize for the delay in syncing versions between GitHub and the Moodle plugins directory.

Current version is now 3.6.6. See the [changelog](https://github.com/projectestac/moodle-mod_geogebra/blob/master/CHANGES.txt) for details.
