### ISSUE TITLE
syntax error in locallib.php line 1429

### ISSUE THREAD

**Issue by febriq** [projectestac/moodle-mod_geogebra#86]
I got this error when entering the course backup page in Moodle 3.0.9+ after upgrading Geogebra plugin to v3.6.10 (2023032100). I deleted a ": stdClass" on line 1429 of locallib.php. Now it seems to work again. Just wanted to report that.

**Comment by toniginard** [comment]
Thanks @febriq. Closing as this is an old issue. It is likely an issue originated by and old version of PHP.


Best wishes,

Toni
