### ISSUE TITLE
Description appears twice

### ISSUE THREAD

**Issue by gilhoo** [projectestac/moodle-mod_geogebra#87]
The description part of my Geogebra activity is displayed twice in Moodle.
I have installed the latest version of the plugin (3.6.10) and I am on Moddle 4.1.3.
I tried changing the Moodle's theme to see if this was related to a misinterpretation of the CSS but it is not.
<img width="1153" alt="description_twice" src="https://github.com/projectestac/moodle-mod_geogebra/assets/46225463/8607f777-6e38-4ec2-becd-19f30658a971">

**Comment by toniginard** [comment]
Fixed since version 3.6.11. Thanks for your contribution!


Toni
