### ISSUE TITLE
string('grade') is deprecated

### ISSUE THREAD

**Issue by tholudwig** [projectestac/moodle-mod_geogebra#90]
With[ MDL-71118](https://tracker.moodle.org/browse/MDL-71118) and later [MDL-71570](https://tracker.moodle.org/browse/MDL-71570), the long-string 'grade' was removed and replaced by 'gradenoun' and 'gradeverb' respectively.

The background is the different use of verbs and nouns in different languages.

**Comment by toniginard** [comment]
Fixed in latest version. Thanks for your contribution!


Toni
