### ISSUE TITLE
Line creation tool automatically draws a vertical line 

### ISSUE THREAD

**Issue by Pitoucol** [projectestac/moodle-mod_geogebra#95]
Hello

We have a particular problem with moodle plugin, when we try to draw lines. 

In some cases, when we use the line creation tool, at the first clic (when you have to set two point), the line is automatically created, and it is vertical, every time we see that bug, the line is vertical. 
And just after, sometimes, but sometimes not, we can set the first point, and after moving the mouse, we are able to set the second point. 

So, it's better with the screenshot.

https://github.com/projectestac/moodle-mod_geogebra/assets/70409859/1196f6d3-9a8c-404a-b9f9-64badb747b08

Moodle plugin is 3.6.9 and moodle install is 4.1
We haven't this bug in moodle 3.11
Tested and reproduced on chrome, firefox, brave (latest versions), but not every time. Sometimes it' works fine for four - five attempts, and then the bug appears. Sometimes the bug is present from the very first attempt.

**Comment by murkle** [comment]
That's fixed in the latest GeoGebra version (v814)

**Comment by Pitoucol** [comment]
Ok, thanks for your answer. 
but is v814 in 3.6.10 ? I just saw that there where a new plugin version (latest version isn't updated in main page).

Many thanks.

**Comment by murkle** [comment]
Sorry, no idea. Probably it needs telling to use the new version

**Comment by toniginard** [comment]
Hi, @Pitoucol,

The plugin mod_geogebra doesn't not include the GeoGebra files. They are loaded from the official GeoGebra site. As long as this issue is from one year ago and hasn't had any other comment, I close it.


Best wishes,

Toni
