### ISSUE TITLE
Please test for newer Moodle branches

### ISSUE THREAD

**Issue by germanvaleroelizondo** [projectestac/moodle-mod_geogebra#97]
This is a very useful plugin for many moodlers.
It would be even better if it were marked as available for newer Moodle branches up to 4.4.

**Comment by toniginard** [comment]
Hi, @germanvaleroelizondo,

I have just released a new version and it's been tested and made available to versions from 4.0 to 4.4.


Best wishes,

Toni

**Comment by germanvaleroelizondo** [comment]
Thanks a lot Toni.
